### ISSUE TITLE
Make metrics optional

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#10]
Really like the idea of this service. It is very minimal and serves a very specific purpose. Thanks for the work!

My requirement is to only be alerted when a container is completely absent. I can achieve this by setting `min-procs` to 1. Therefore I´m not interested in any cpu oder memory usage warnings. 

Would it be possible to only watch the metrics which are actually defined in the config file?

**Comment by deltaskelta** [comment]
Just to make sure I understand you correctly, you want to just follow the metrics defined in the config and for you that metric is just that the container is running?

**Comment by alexlawrence** [comment]
@deltaskelta Yes, exactly. For my special case I just want to monitor containers and be alerted when they crash. In other cases I might only be interested in cpu monitoring and don´t care about memory usage.

**Comment by deltaskelta** [comment]
ok I like that idea, I will try to rewrite this soon and get it working that way

**Comment by deltaskelta** [comment]
commit 6cbfedfb85f4511a922441dfb34fdc6f16c756ca fixes the underlying issue, but there is still some more work to be done before releasing it

**Comment by deltaskelta** [comment]
FIxed in latest release 765c7273ecbffdf9a4e514a3ba83219f4fb6e2f5
