### ISSUE TITLE
Prevent crash when container does not exist or is removed

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#11]
Currently, the program exits/crashes when a container does not exist or is removed.
In my opinion the service should keep running and only send an alert about the circumstance.

What do you think?

**Comment by deltaskelta** [comment]
You are right, it should just alert you. I will look into it

**Comment by deltaskelta** [comment]
commit 6cbfedfb85f4511a922441dfb34fdc6f16c756ca fixes the underlying issue, but I need to fix up some more things before merging it into the master and releasing the binaries

**Comment by deltaskelta** [comment]
Fixed in latest release 765c7273ecbffdf9a4e514a3ba83219f4fb6e2f5
