### ISSUE TITLE
Alternative installation method

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#12]
Disclaimer: I do not have any experience with go(lang).

Is there any possible alternative method to install this service?  `go get` takes forever to download docker (which is a dependency I assume).

**Comment by deltaskelta** [comment]
I did provide prebuilt binaries before, but I took down the server they were on at the time. I do not see a way to avoid importing docker to get this done so I think providing prebuilt binaries would be the best route. 

Do you know anywhere where they can be hosted at?

**Comment by alexlawrence** [comment]
@deltaskelta How about the following:
- create a separate git branch named "release"
- when changing stuff build the project and commit/push the binaries to this branch
- additionally add and push a tag pointing to this commit

This way Github will pick up the tag and display it as release.

**Comment by deltaskelta** [comment]
oh ok good idea. I was thinking that the binaries would be too big for the repo but I guess no. I will do this soon

**Comment by alexlawrence** [comment]
I don´t know if they would be too big. It would definitely increase the size of the overall repository and therefore slow down `git clone`. What size are we talking about? A few mb?

**Comment by deltaskelta** [comment]
I added a dist folder in the newly created `release` branch which will contain the most recently built binaries. They have been linked to in the main README file.

The builds are about 7mb for each OS. If revision control makes them too big in the future, I may have to remove it...

https://github.com/deltaskelta/docker-alertd/tree/release
https://github.com/deltaskelta/docker-alertd/blob/master/README.md

**Comment by alexlawrence** [comment]
That´s nice. Thanks!

> The builds are about 7mb for each OS. If revision control makes them too big in the future, I may have to remove it...

I understand. Maybe a separate repository would solve this issue? Something like `docker-alertd-dist` or  `docker-alertd-prebuilt`?

**Comment by deltaskelta** [comment]
perhaps, I will keep that in mind if I run into that issue in the future. I'll have to see how git handles it for now
