### ISSUE TITLE
Container existence check

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#17]
I want to check for the existence of a container (regardless of state). 
In my case the container is initially stopped / not running.
As far as I understand the correct way to do this is the following:

```
containers:
  - name: xyz
```

However, with this I´m getting alerts when the container starts and recovery alerts when the container stops. It looks like the above configuration causes docker-alertd to expect the container not to be running.

Do you have any idea what the problem could be?

**Comment by deltaskelta** [comment]
hmm yeah I guess the default value of the config struct after it reads it in would be false. So when checkers are appended here it is not expected running...

https://github.com/deltaskelta/docker-alertd/blob/master/cmd/monitor.go#L71

And then here...as long as the container exists and it got Jason from the docker engine it will continue checking for the default false value...

https://github.com/deltaskelta/docker-alertd/blob/master/cmd/alertd_container.go#L71

I'll have to think about the best way to solve the issue

**Comment by deltaskelta** [comment]
@alexlawrence Ive got a few ideas to go about fixing it but I wont have much time to go about testing them this week.

I think that a nil value will be valid if passed into the config which means that is you didnt care about runming state, the option would be included in the config but it would be `expectedRunning: nil`

If that doesn't work we could make the value an enumeration of strings or maybe nest it in some way to allow for more checks that only true or false. 

Ill try to get something up as soon as I can

**Comment by alexlawrence** [comment]
@deltaskelta Thanks for the responses. I tried passing `nil` as value but that results in the following error:

```
docker-alertd[23706]: * cannot parse 'Containers[5].ExpectedRunning' as bool: strconv.ParseBool: parsing "nil": invalid syntax
```

**Comment by deltaskelta** [comment]
Yes I will have to change the bool to be a pointer and then it should work. I will have time within the next few days to get a working fix up and running. Hope its not too inconvenient as it is.

**Comment by alexlawrence** [comment]
Sounds great. Thanks!

> Hope its not too inconvenient as it is.

Of course not :) It´s already very helpful that you created this component in the first place.

**Comment by deltaskelta** [comment]
I have fixed the issue by making all the checks pointers, which means if they are absent, that will be taken into account and that check will be completely ignored rather than initialized as a `zero value` as it was before. 

All tests are passing and it should be fixed now!
