### ISSUE TITLE
Differentiation and customization of alerts / e-mails

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#19]
These are actually two separate features.

1. Differentiation between e-mails

It would help to be able to define different subjects for e-mail alerts depending on the type of alert (failure or recovery). Example: "container failure" vs. "container recovery"

2. Customization of alerts

It would also be nice to provide a custom text or even use a template for individual content in alerts/e-mails.

Both features are nice to have.

**Comment by deltaskelta** [comment]
Hmm yeah number 1 shouldn't be too difficult to implement so I'll look into it soon.

As for number 2...

How would you see this working from the point of view of the config file?
Would it be better to just make a better formatted stock message?

**Comment by alexlawrence** [comment]
> Would it be better to just make a better formatted stock message?

Yes, that would be completely sufficient. 
Templating makes things unnecessarily complicated.

**Comment by deltaskelta** [comment]
Ok, I'm open to ideas about how the message should be formatted. What is your opinion?

**Comment by alexlawrence** [comment]
So as said it would be nice to have two different subjects (failure and recovery). This could be done by using the subject from configuration file as prefix and appending "failure" or "recovery".

For the message itself it would be sufficient to use newlines and rearrange it to make it more readable.

```
<"failure"|"recovery">
tracking: <metric>
expected state: <expectedState>
current state: <currentState>
```
